# This is an example Starter pipeline configuration
# Use a skeleton to build, test and deploy using manual and parallel steps
# -----
# You can specify a custom docker image from Docker Hub as your build environment.

image: caerfyre/pantonialdev-examplevue

pipelines:
  default:
    - parallel:
        - step:
            image: node
            services:
              - node
            name: 'Unit Tests'
            caches:
              - node
            script:
              - npm install
              - npm run test:unit
        - step:
            image: cypress-img
            services:
              - cypress-img
            name: 'Integration Tests (E2E)'
            caches:
              - yarn
              - cypress
              - node
            script:
              - npm install cypress --save-dev
              - npm run test:e2e
        - step:
            name: 'Lint'
            script:
              - echo "Linting scripts..."
        - step:
            name: 'Security scan'
            script:
              - echo "Your security scan goes here..."

    # The following deployment steps will be executed for each pipeline run. To configure your steps and conditionally deploy see https://support.atlassian.com/bitbucket-cloud/docs/configure-bitbucket-pipelinesyml/
    - step:
        name: 'Deployment to Staging'
        deployment: staging
        script:
          - echo "Your deployment to staging script goes here..."
    - step:
        name: 'Deployment to Production'
        deployment: production
        trigger: 'manual'
        script:
          - echo "Your deployment to production script goes here..."

definitions:
  services:
    node:
      image: node:latest
    cypress-img:
      image: cypress/base:10
  caches:
    yarn: $HOME/.cache
    cypress: $HOME/.cache/Cypress