version: "2"
services:
  main:
    container_name: pantonialdev-examplevue-main
    image: node:lts-alpine
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=development
    volumes:
      - ./:/home/node/app
    expose:
      - "8080"
    ports:
      - "8080:8080"
    command: "npm run serve -- --port 8080"
    stdin_open: true
    tty: true
